// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuzpyosdcwmmliyuvavv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1enB5b3NkY3dtbWxpeXV2YXZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMDYwMDQsImV4cCI6MjA1MjY4MjAwNH0.RaMIBHFtGlIbOTBd5c55NeRVzSCyUwvNEX9-A7NDO7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);